export interface Plan{
    id?:string|undefined,
    userId:string,
    name:string,
    location:string,
    taskName:string,
    createdDate:Date,
    updatedDate:Date,
    plannedStartDate:Date,
    plannedEndDate:Date,
    task:string,
    notify:boolean,
    notifyDate:Date,
    isCompleted:boolean,
}